// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';

export function ExecuteQuery(arg1:string):Promise<database.QueryResult>;

export function GetSchema(arg1:string):Promise<Array<database.Column>>;

export function GetTables():Promise<Array<string>>;
