// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteQuery(arg1) {
  return window['go']['main']['App']['ExecuteQuery'](arg1);
}

export function GetSchema(arg1) {
  return window['go']['main']['App']['GetSchema'](arg1);
}

export function GetTables() {
  return window['go']['main']['App']['GetTables']();
}
